version: '3'

services:
  app:
    build: ./app
    ports:
      - "8080:80"
    links:
      - mongodb
    environment:
      - GIN_MODE=release
      - MONGO_URL=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/alekseigusakov/Projects/MongoStore/database:/data/db